Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('comment/<int:pizza_id>/', views.comment, name='comment'),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=50)

    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name[:50]}..."

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text[:50]}..."

pizzas/forms.py
from django import forms
from .models import Pizza, Topping, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Comment:'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm
# Create your views here.
def index(request):
    """The home page for Pizzas."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizza options available."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            form.save()
            return redirect('pizzas:pizza',pizza_id=pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/comment.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Tommy's Pizzeria</a>
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}
{% endblock content %}

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

    <p>Add a comment:</p>

<form action="{% url 'pizzas:comment' pizza.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>This is where we sell...</p>



<pre>
            88                                 
            ""                                 
                                       
8b,dPPYba,  88 888888888 888888888 ,adPPYYba,  
88P'    "8a 88      a8P"      a8P" ""     `Y8  
88       d8 88   ,d8P'     ,d8P'   ,adPPPPP88  
88b,   ,a8" 88 ,d8"      ,d8"      88,    ,88  
88`YbbdP"'  88 888888888 888888888 `"8bbdP"Y8  
88                                             
88                                             
</pre>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizza: {{ pizza }}</p>

    <p>Toppings:</p>
    <ul>
        {% for topping in toppings %}
            <li>
                <p>{{ topping.name|linebreaks }}</p>
            </li>
        {% empty %}
            <li>There are no toppings for this pizza yet.</li>
        {% endfor %}
    </ul>

    <p>
        <a href="{% url 'pizzas:comment' pizza.id %}">Add a comment</a>
    </p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizzas</p>

    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
            </li>
        {% empty %}
            <li>No pizzas have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}